### ISSUE TITLE
is this project work on windows?

### ISSUE THREAD

**Issue by komilaria** [psyai-net/SelfTalk_release#1]

**Comment by ZiqiaoPeng** [comment]
Sorry, we didn't adapt it for Windows. You can try running it on Linux.

**Comment by Consrr** [comment]
Hey guys, I've succcessfully run this demo project on Windows. Firstly, u can follow the instructions on https://github.com/johnbanq/mesh/tree/fix/MSVC_compilation
to install the package "mesh" on Windows . Then we can change the code of"demo_cast" a litttle bit:
1. Delete the first line "os.environ['PYOPENGL_PLATFORM'] = 'egl'",cuz EGL is hard to use on Windows( I've tried a lot on this instruction but failed)
2. Change the "render_sequence_meshes" function into:def render_sequence_meshes(audio_fname, sequence_vertices, template, out_path, uv_template_fname='',
                           texture_img_fname=''):
    if not os.path.exists(out_path):
        os.makedirs(out_path)

    tmp_video_path = os.path.join(out_path, 'temp_video.mp4')

    try:
        fourcc = cv2.VideoWriter_fourcc(*'mp4v')  
        writer = cv2.VideoWriter(tmp_video_path, fourcc, 30, (800, 800), True)

        if not writer.isOpened():
            raise ValueError("无法创建视频写入器")

        center = np.mean(sequence_vertices[0], axis=0)
        for i_frame in range(sequence_vertices.shape[0]):
            render_mesh = Mesh(sequence_vertices[i_frame], template.f)
            img = render_mesh_helper(render_mesh, center)
            writer.write(img)

        writer.release()

        cap = cv2.VideoCapture(tmp_video_path)
        if not cap.isOpened():
            raise ValueError("生成的视频文件无效")
        frame_count = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
        cap.release()
        print(f"成功生成 {frame_count} 帧视频")

        video_fname = os.path.join(out_path, 'video.mp4')
        ffmpeg_cmd = [
            'ffmpeg',
            '-y',
            '-i', tmp_video_path,
            '-i', audio_fname,
            '-c:v', 'libx264',
            '-c:a', 'aac',
            '-pix_fmt', 'yuv420p',
            '-shortest',
            video_fname
        ]

        print("执行FFmpeg命令:", ' '.join(ffmpeg_cmd))
        subprocess.run(ffmpeg_cmd, check=True)

    except Exception as e:
        print(f"错误: {str(e)}")
        raise
    finally:
        if os.path.exists(tmp_video_path):
            try:
                os.remove(tmp_video_path)
            except:
                pass

And thats all. I am a rookie for coding,hoping you can successfully running this project on Windows :)
