### ISSUE TITLE
How to run the demo with my custom subject?

### ISSUE THREAD

**Issue by alchemician** [psyai-net/SelfTalk_release#3]
Hello author - thanks for the fantastic work!

I am able to test the pretrained models with the subjects present and I am currently looking to try with my custom video. Can you please guide me how to create vertices_npy folder for my video?

Thank you in advance!

**Comment by ZiqiaoPeng** [comment]
You can refer to the Reconstruct template from images section in [VOCA](https://github.com/TimoBolkart/voca?tab=readme-ov-file#reconstruct-template-from-images) to make your data.
